name: HACS Action

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-hacs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "plugin"
